name: Deploy to Branch

on:
  push:
    branches:
      - main  # Replace 'main' with your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          npm install
          npm run build  # Replace with your build command

      - name: Deploy to Branch
        uses: JamesIves/github-pages-deploy-action@4.1.3  # Use a suitable deploy action
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # GitHub token with repo access
          BRANCH: deploy  # Branch to deploy to (replace with your desired branch)
          FOLDER: dist  # Folder containing the built files
